name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  code-fetch:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest ]
        node-version: [ 12.x, 14.x, 16.x ]
    name: "Fetch the Code"
    steps:
    - uses: actions/checkout@v2
    - name: Staus of Aciton
      run: |
          echo Fetched the Code Successfully!
          
  env-setup:
    if: always()
    needs: code-fetch
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest ]
        node-version: [ 12.x, 14.x, 16.x ]
    name: "Setting Up Enviroment"
    steps:
    - uses: actions/checkout@v2
    - name: Using Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
          echo Installed NodeJS - ${{ matrix.node-version }}
          
  dependecies:
    if: always()
    needs: [code-fetch, env-setup]
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest ]
        node-version: [ 12.x, 14.x, 16.x ]
    name: "Installing Project Dependencies"
    steps:
    - uses: actions/checkout@v2
    - name: Using Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i

  build:
    if: always()
    needs: [code-fetch, env-setup, dependecies]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
        node-version: [ 12.x, 14.x, 16.x ]
    name: "Building the Project"
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run build

  test:
    if: always()
    needs: [code-fetch, env-setup, dependecies, build]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
        node-version: [ 12.x, 14.x ]
    name: "Testing the Code"
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run test

  deploy-test:
    if: always()
    needs: [code-fetch, env-setup, dependecies, build, test]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ 12.x, 14.x, 16.x ]
    name: "Netlify Deploy"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Deploy Site
        run: curl -X POST -d {} ${{ secrets.TRIGGER_NETLIFY_DEPLOY }}

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm i
      - run: npm semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
