name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  node_modules:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest ]
        node-version: [ 12.x, 14.x, 16.x ]
    name: "Fetch the Code"
    steps:
    - name: Pull the Code From Repo
    - uses: actions/checkout@v2